### ISSUE TITLE
the get range function switch case checks the wrong thing

### ISSUE THREAD

**Issue by lpancoast-nyu** [sparkfun/SparkFun_ADXL313_Arduino_Library#1]
the cases should be 0/1/2/4 for 0.5/1/2/4 range instead of using ADXL313_RANGE_05_G etc

**Comment by lewispg228** [comment]
Thank you for bringing this to our attention. This has been fixed. Please see [this commit](https://github.com/sparkfun/SparkFun_ADXL313_Arduino_Library/commit/32bc8376500c4d0daf24bee45ebe6ef864514c24) for details, and use the latest release (v1.0.3).
