### ISSUE TITLE
Compilation problem SparkFun_ADXL313_Arduino_Library-master

### ISSUE THREAD

**Issue by Paxiii** [sparkfun/SparkFun_ADXL313_Arduino_Library#3]
Dear All! 

There is compilation problem with SparkFun_ADXL313_Arduino_Library-master.

Comlipation results:

C:\Users\lupierzp\Documents\Arduino\libraries\SparkFun_ADXL313_Arduino_Library-master\src\SparkFunADXL313.cpp: In member function 'boolean ADXL313::beginSPI(uint8_t, SPIClass&)':
C:\Users\lupierzp\Documents\Arduino\libraries\SparkFun_ADXL313_Arduino_Library-master\src\SparkFunADXL313.cpp:78:21: error: no matching function for call to 'SPIClass::begin(int&)'
  _spiPort->begin(_CS);
                     ^
In file included from C:\Users\lupierzp\Documents\Arduino\libraries\SparkFun_ADXL313_Arduino_Library-master\src\SparkFunADXL313.h:46:0,
                 from C:\Users\lupierzp\Documents\Arduino\libraries\SparkFun_ADXL313_Arduino_Library-master\src\SparkFunADXL313.cpp:34:
D:\ProgramFiles\Arduino\hardware\arduino\avr\libraries\SPI\src/SPI.h:159:15: note: candidate: static void SPIClass::begin()
   static void begin();
               ^~~~~
D:\ProgramFiles\Arduino\hardware\arduino\avr\libraries\SPI\src/SPI.h:159:15: note:   candidate expects 0 arguments, 1 provided
C:\Users\lupierzp\Documents\Arduino\libraries\SparkFun_ADXL313_Arduino_Library-master\src\SparkFunADXL313.cpp: In member function 'void ADXL313::readFromI2C(byte, int, byte*)':
C:\Users\lupierzp\Documents\Arduino\libraries\SparkFun_ADXL313_Arduino_Library-master\src\SparkFunADXL313.cpp:711:43: warning: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second:
  _i2cPort->requestFrom(_deviceAddress, num);  // Request 6 Bytes
                                           ^
In file included from C:\Users\lupierzp\Documents\Arduino\libraries\SparkFun_ADXL313_Arduino_Library-master\src\SparkFunADXL313.h:45:0,
                 from C:\Users\lupierzp\Documents\Arduino\libraries\SparkFun_ADXL313_Arduino_Library-master\src\SparkFunADXL313.cpp:34:
D:\ProgramFiles\Arduino\hardware\arduino\avr\libraries\Wire\src/Wire.h:68:13: note: candidate 1: uint8_t TwoWire::requestFrom(int, int)
     uint8_t requestFrom(int, int);
             ^~~~~~~~~~~
D:\ProgramFiles\Arduino\hardware\arduino\avr\libraries\Wire\src/Wire.h:65:13: note: candidate 2: uint8_t TwoWire::requestFrom(uint8_t, uint8_t)
     uint8_t requestFrom(uint8_t, uint8_t);
             ^~~~~~~~~~~
exit status 1
Błąd kompilacji dla płytki Arduino Leonardo.

Could you check/fix this?

Best Regards
Paxiii

**Comment by lgaszto** [comment]
Same issue here:

C:\Users\gasztonyi.laszlo\Documents\Arduino\libraries\SparkFun_ADXL313_Arduino_Library\src\SparkFunADXL313.cpp: In member function 'boolean ADXL313::beginSPI(uint8_t, SPIClass&)':
C:\Users\gasztonyi.laszlo\Documents\Arduino\libraries\SparkFun_ADXL313_Arduino_Library\src\SparkFunADXL313.cpp:78:21: error: no matching function for call to 'SPIClass::begin(int&)'
  _spiPort->begin(_CS);
                     ^
In file included from C:\Users\gasztonyi.laszlo\Documents\Arduino\libraries\SparkFun_ADXL313_Arduino_Library\src\SparkFunADXL313.h:46:0,
                 from C:\Users\gasztonyi.laszlo\Documents\Arduino\libraries\SparkFun_ADXL313_Arduino_Library\src\SparkFunADXL313.cpp:34:
C:\Users\gasztonyi.laszlo\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.8.6\libraries\SPI\src/SPI.h:159:15: note: candidate: static void SPIClass::begin()
   static void begin();
               ^~~~~
C:\Users\gasztonyi.laszlo\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.8.6\libraries\SPI\src/SPI.h:159:15: note:   candidate expects 0 arguments, 1 provided
In file included from C:\Users\gasztonyi.laszlo\Documents\Arduino\libraries\SparkFun_ADXL313_Arduino_Library\src\SparkFunADXL313.h:45:0,
                 from C:\Users\gasztonyi.laszlo\Documents\Arduino\libraries\SparkFun_ADXL313_Arduino_Library\src\SparkFunADXL313.cpp:34:
C:\Users\gasztonyi.laszlo\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.8.6\libraries\Wire\src/Wire.h: In member function 'void ADXL313::readFromI2C(byte, int, byte*)':
C:\Users\gasztonyi.laszlo\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.8.6\libraries\Wire\src/Wire.h:68:13: note: candidate 1: uint8_t TwoWire::requestFrom(int, int)
     uint8_t requestFrom(int, int);
             ^~~~~~~~~~~
C:\Users\gasztonyi.laszlo\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.8.6\libraries\Wire\src/Wire.h:65:13: note: candidate 2: uint8_t TwoWire::requestFrom(uint8_t, uint8_t)
     uint8_t requestFrom(uint8_t, uint8_t);
             ^~~~~~~~~~~

exit status 1

Compilation error: exit status 1

Could you please check and fix it?

**Comment by lewispg228** [comment]
It looks like the SPI Class `begin()` no longer takes a CS pin as an argument. This is unnecessary anyways, because CS pin control is handled in this library. Removing this allows it to compile. Once I get a chance to verify this with actual hardware, then we can do a release with this update.

**Comment by lewispg228** [comment]
This has been fixed and verified with hardware (ATMega328 and Artemis). Thank you for bringing this to our attention. Please see [this commit](https://github.com/sparkfun/SparkFun_ADXL313_Arduino_Library/commit/32bc8376500c4d0daf24bee45ebe6ef864514c24) for details, and use the latest release (v1.0.3).
