### ISSUE TITLE
Compilation error with example 1 on Redboard Artemis

### ISSUE THREAD

**Issue by DesktopMan** [sparkfun/SparkFun_ADXL313_Arduino_Library#5]
Trying to compile Example1_Basic_Readings.ino:

```
Arduino\libraries\SparkFun_ADXL313_Arduino_Library\src\SparkFunADXL313.cpp: In member function 'boolean ADXL313::beginSPI(uint8_t, arduino::SPIClass&)':
Arduino\libraries\SparkFun_ADXL313_Arduino_Library\src\SparkFunADXL313.cpp:78:21: error: no matching function for call to 'arduino::HardwareSPI::begin(int&)'
  _spiPort->begin(_CS);
                     ^
In file included from Arduino15\packages\SparkFun\hardware\apollo3\2.2.1\libraries\SPI\src/SPI.h:10,
                 from Arduino\libraries\SparkFun_ADXL313_Arduino_Library\src\SparkFunADXL313.h:46,
                 from Arduino\libraries\SparkFun_ADXL313_Arduino_Library\src\SparkFunADXL313.cpp:34:
Arduino15\packages\SparkFun\hardware\apollo3\2.2.1/cores/arduino/mbed-bridge/core-api/api/HardwareSPI.h:123:18: note: candidate: 'virtual void arduino::HardwareSPI::begin()'
     virtual void begin() = 0;
                  ^~~~~
Arduino15\packages\SparkFun\hardware\apollo3\2.2.1/cores/arduino/mbed-bridge/core-api/api/HardwareSPI.h:123:18: note:   candidate expects 0 arguments, 1 provided
Arduino\libraries\SparkFun_ADXL313_Arduino_Library\src\SparkFunADXL313.cpp:79:12: error: 'arduino::SPIClass' {aka 'class arduino::HardwareSPI'} has no member named 'setDataMode'
  _spiPort->setDataMode(SPI_MODE3);
            ^~~~~~~~~~~

exit status 1

Compilation error: exit status 1
```

**Comment by lewispg228** [comment]
Hi @DesktopMan ,
Thanks for your message here. I was just working on this exact problem (similar Artemis-based  hardware) yesterday and found a solution.

The [CS pin control is handled within the ADXL313 library](https://github.com/sparkfun/SparkFun_ADXL313_Arduino_Library/blob/master/src/SparkFunADXL313.cpp#L729), so we don't really need to pass it to the SPI.begin() function. If we omit this argument, then the compile error goes away.

The setDataMode() function seems to have become depreciated, so the best way to make it SPI_MODE3 is to pass an SPISettings object inside the SPI function.

You need to make two small adjustments to the header file here:

https://github.com/sparkfun/SparkFun_ADXL313_Arduino_Library/blob/master/src/SparkFunADXL313.cpp#L78

https://github.com/sparkfun/SparkFun_ADXL313_Arduino_Library/blob/master/src/SparkFunADXL313.cpp#L79

![image](https://github.com/sparkfun/SparkFun_ADXL313_Arduino_Library/assets/601236/297e9438-e64a-4ac5-b44d-6d902ee3feb3)

Hope this helps and let us know how it goes,
Pete

PS. we will be working on a more permanent fix for this with a new release asap.

**Comment by lewispg228** [comment]
Here's the code adjustment too, for easier copy/paste.

	//_spiPort->begin(_CS); // throws a compile error, no such function
	_spiPort->begin();
	//_spiPort->setDataMode(SPI_MODE3); // old way of doing SPI settings, now you must pass in an SPISettings object
	_spiPort->beginTransaction(SPISettings(2000000, MSBFIRST, SPI_MODE3));

**Comment by lewispg228** [comment]
This has been fixed. Please see [this commit](https://github.com/sparkfun/SparkFun_ADXL313_Arduino_Library/commit/32bc8376500c4d0daf24bee45ebe6ef864514c24) for details, and use the latest release (v1.0.3).
