### ISSUE TITLE
setAxisOffset- Incorrect Scale Factor in Example Code

### ISSUE THREAD

**Issue by AmadeaVoxelis** [sparkfun/SparkFun_ADXL313_Arduino_Library#6]
In the example code, the setAxisOffset function has a comment which indicates that the scale factor is 15.6 mg/LSB, but when you look in the datasheet you find that the scale factor is actually 3.9 mg/LSB for this chip. 

It appears that this issue is related to the comment at the top of the .h file which indicates that this library was written by tweaking a library for a different chip, and so perhaps this misleading comment is residual from that other library. Changing this comment would be helpful for future users. 

Here's what it reads now:
```
/********************* OFSX, OFSY and OFSZ BYTES ********************/
/*                           ~ SET & GET                            */
// OFSX, OFSY and OFSZ: User Offset Adjustments in Twos Complement Format
// Scale Factor of 15.6mg/LSB
void ADXL313::setAxisOffset(int x, int y, int z) {
```

and here's what it SHOULD read:
```
/********************* OFSX, OFSY and OFSZ BYTES ********************/
/*                           ~ SET & GET                            */
// OFSX, OFSY and OFSZ: User Offset Adjustments in Twos Complement Format
// Scale Factor of 3.9 mg/LSB
void ADXL313::setAxisOffset(int x, int y, int z) {
```

**Comment by lewispg228** [comment]
Hi @AmadeaVoxelis , 
Thank you for bringing this to our attention. Indeed, you are correct. The comment was not updated to reflect the correct scale factor. Sorry for this oversight, and we hope it didn't cause you too much trouble.

We will work to get this updated and do a new release of the library asap.

Thanks again and we hope your project using the ADXL313 is going well!
-Pete

**Comment by lewispg228** [comment]
Thanks again for bringing this to our attention. This has been fixed. Please see [this commit](https://github.com/sparkfun/SparkFun_ADXL313_Arduino_Library/commit/32bc8376500c4d0daf24bee45ebe6ef864514c24) for details, and use the latest release (v1.0.3).
